[project]
name = "final project"
version = "0.1.0"
requires-python = ">=3.7"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project.optional-dependencies]
test = [
  "pytest"
  ]
