on:
  pull_request:
  push:
    branches:
      - main
       
jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
        - "3.11"
        
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
      
    - name: Install package
      run: python -m pip install -e .[test]

    - name: Install package
      run: python -m pip install matplotlib
      
    - name : install nox
      run: pip install nox
      
    - name: run nox
      run: nox -s tests
